include netinet/ether.h before linux/if_ether.h
musl does not include OS specific defines like uclibc/glibc
so we changed the linux kernel headers such that if userspace
if_ether.h is included then we avoid the duplicate defines in kernel
headers. But the logic is defeated if linux/if_ether.h is included
before netinet/ether.h, so lets change the order

usr/include/netinet/if_ether.h:96:8: error: redefinition of 'struct
ethhdr'

include wait.h for WEXITED definition

src/libsystemd/sd-event/test-event.c:101:77: error: 'WEXITED' undeclared
(first use in this function)

Signed-off-by: Khem Raj <raj.khem@gmail.com>